'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../..'),p=path.join(root,'tools/windows-installer');
const iss=fs.readFileSync(path.join(p,'setup.iss'),'utf8'),pin=JSON.parse(fs.readFileSync(path.join(p,'toolchain.json')));
for(const line of ['PrivilegesRequired=lowest','ArchitecturesAllowed=x64os','CloseApplications=no','RestartApplications=no','UninstallFilesDir={app}\\uninstall','DisableDirPage=yes','DisableProgramGroupPage=yes','DisableReadyPage=yes','DefaultDirName={localappdata}\\Programs\\K-SESSION-Beta','InfoBeforeFile={#Generated}\\install-info.txt','UsePreviousAppDir=no']) assert.ok(iss.split(/\r?\n/).includes(line),line);
assert.equal(pin.version,'6.7.3');assert.match(pin.sha256,/^[a-f0-9]{64}$/);
assert.ok(iss.includes("GetDateTimeString('yyyymmddhhnnss', '-', ':')"));
assert.ok(!/GetDateTimeString\([^\n]*, '', ''\)/.test(iss),'Char arguments cannot be empty strings');
assert.ok(!iss.includes('[UninstallDelete]'));assert.ok(!iss.includes('[InstallDelete]'));
for(const forbidden of ['taskkill','RestartManager','runascurrentuser','uninsdeletekeyifempty'])assert.ok(!iss.includes(forbidden));
for(const name of ['PrepareToInstall','InitializeUninstall','VerifyInstalled','RunningProduct','AcquireExistingInstanceLock'])assert.ok(iss.includes(name));
console.log('INSTALLER CONTRACT PASS');
assert.ok(iss.includes("CreateInputDirPage(wpInfoBefore, '业务数据与附件保存位置'"));
assert.equal((iss.match(/Parameters: "--instance/g)||[]).length,3,'desktop, menu and finish must bind instance');
assert.ok(iss.includes('instance-binding.ini'));
assert.ok(iss.includes('KSESSION_DATA_SWITCH_UNCONFIRMED'));
assert.ok(/Exec\(LocationChecker, Mode \+ .*WizardDirValue/.test(iss),'data page validates before app constant initialization');
console.log('R2 DATA LOCATION CONTRACT PASS');
